### ISSUE TITLE
从 VSCode 里复制的代码粘贴会有问题

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_auto_codeblock#3]
https://github.com/user-attachments/assets/952d36b0-6de2-428c-b2f2-ae6075185d66

**Comment by zxkmm** [comment]
推送了 13012dad7b224e730ce014517dd5dd2556c1623b
但看起来没有效果。
不知道vscode复制出来的东西是什么样子，我要找个剪贴板内容查看器（目前没找到）

**Comment by zxkmm** [comment]
这个好像工程量有点大啊，vscode复制出来的代码似乎是html，思源似乎还自己解析了（而且似乎还蜜汁自动识别了语言）

**Comment by zxkmm** [comment]
https://github.com/siyuan-note/siyuan/issues/12429

**Comment by zxkmm** [comment]
暂时用@frostime 的方案解决，还是希望思源官方处理一下
