### ISSUE TITLE
建议删除markdown识别

### ISSUE THREAD

**Issue by CongSec** [zxkmm/siyuan_auto_codeblock#5]
右键复制图片粘贴变成代码块，从别markdown语法的软件里复制到思源变成代码块，从别的软件复制过来大多数是为了复制笔记而不是弄成代码块
![image](https://github.com/user-attachments/assets/cf5695d2-36e3-4a08-896b-5191815162db)

**Comment by zxkmm** [comment]
感谢反馈！
1. 图片的问题下版本会修复
2. markdown识别下版本做成可选开关

**Comment by CongSec** [comment]
感觉markdown放入代码块的需求比较少，默认关闭即可，因该保持插件的简洁性

**Comment by zxkmm** [comment]
主要是目前计划中的两个特性分别是语言黑名单和语言fallback名单，所以语言黑名单刚好可以用，我打算默认添加markdown进去。
至于代码简洁性的话我个人感觉暂时还不用担心，因为这个即使加了名单以后时间复杂度也不变：O(1)~O(n)
然后经过对其他闭源+混淆的插件试用下来，感觉性能差别应该是无法感知。闭源+混淆的插件时间复杂度和空间复杂度都是我的插件的几万倍，但性能减弱不太明显。
再次感谢！

**Comment by zxkmm** [comment]
e858c217184e8cd0f268a53f0c457eb65b2a2989
方便的话测试下黑名单康康（回退名单没有写），谢谢
