### ISSUE TITLE
在代码块内粘贴代码，不需要识别语言

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_auto_codeblock#7]
![image](https://github.com/user-attachments/assets/554fd8b6-a72a-4ec6-9a5a-52c8ddf39efd)

**Comment by zxkmm** [comment]
这个目前可能无法规避，因为我没找到读当前光标所在块内容的方法，所以插件没办法判断你是不是在代码块内部。对于这个解决方法就是只能关掉自动识别，然后需要识别时候就用斜杠菜单来处理。

**Comment by TCOTC** [comment]
那就先这样吧，不过我发现这个保存不起作用，要手动重载才会生效：

![image](https://github.com/user-attachments/assets/ab1d1abd-e28f-4520-aef6-96cee08e1e3b)

**Comment by zxkmm** [comment]
这个有点怪，理论上每次粘贴都读一次插件存储的

**Comment by choyy** [comment]
> 这个目前可能无法规避，因为我没找到读当前光标所在块内容的方法，所以插件没办法判断你是不是在代码块内部。对于这个解决方法就是只能关掉自动识别，然后需要识别时候就用斜杠菜单来处理。

光标所在元素的class名称会多一个`block-focus`，光标在代码块内的话，代码块元素的class会变成`"code-block block-focus"`，所以可以通过`document.getElementsByClassName("code-block block-focus")`这种方式来判断是否在代码块内

**Comment by zxkmm** [comment]
> > 这个目前可能无法规避，因为我没找到读当前光标所在块内容的方法，所以插件没办法判断你是不是在代码块内部。对于这个解决方法就是只能关掉自动识别，然后需要识别时候就用斜杠菜单来处理。
> 
> 光标所在元素的class名称会多一个`block-focus`，光标在代码块内的话，代码块元素的class会变成`"code-block block-focus"`，所以可以通过`document.getElementsByClassName("code-block block-focus")`这种方式来判断是否在代码块内

感谢大佬！我今天下午试一下

**Comment by zxkmm** [comment]
我这边根据这个css获取到的obj是这个，似乎没办法提取有用的信息
![image](https://github.com/user-attachments/assets/096688ac-7e4f-43b3-90f7-1cdb3b79da4f)

**Comment by TCOTC** [comment]
> 光标所在元素的 class 名称会多一个 block-focus

会吗？我这里没有

**Comment by TCOTC** [comment]
我提供一个不同的思路，看当前编辑器面包屑：

![image](https://github.com/user-attachments/assets/3443c576-5cc2-4094-87d2-7a395f1b836c)

p.s. 但我刚刚发现如果是用键盘移动光标的话这个 icon 不会变

**Comment by choyy** [comment]
> 我这边根据这个css获取到的obj是这个，似乎没办法提取有用的信息 ![image](https://private-user-images.githubusercontent.com/24917424/372501291-096688ac-7e4f-43b3-90f7-1cdb3b79da4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTI1NTksIm5iZiI6MTcyNzc5MjI1OSwicGF0aCI6Ii8yNDkxNzQyNC8zNzI1MDEyOTEtMDk2Njg4YWMtN2U0Zi00M2IzLTkwZjctMWNkYjNiNzlkYTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0MTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMjk2NjRiODYxZDhiYWMxYjQxMmRkYjM1ODI0OWViMGJkZjEyYzBlYTI5NGY4ZTBhMDRjZTEyMTYyYWQ0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4a6jjigRbiDAWXnlVff4Og5mQgLp7mscKkJqVkISkqM)

光标不在代码快内是没有内容的，光标在代码块内会返回该代码块的

**Comment by zxkmm** [comment]
> 光标不在代码快内是没有内容的，光标在代码块内会返回该代码块的

我这边尝试了如下操作：
光标在空代码块内部
光标在空块内部
光标在有内容的代码块内部
光标在空普通块内部
光标在有内容普通块内部
似乎都是一样的

**Comment by zxkmm** [comment]
> 我提供一个不同的思路，看当前编辑器面包屑：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/372505946-3443c576-5cc2-4094-87d2-7a395f1b836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTMwNDEsIm5iZiI6MTcyNzc5Mjc0MSwicGF0aCI6Ii83ODQzNDgyNy8zNzI1MDU5NDYtMzQ0M2M1NzYtNWNjMi00MDk0LTg3ZDItN2EzOTVmMWI4MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0MjU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMDZhZmM4ODUxMGE4MjIyYzVjNGNmYjllODFmOGUwMTRkOTNmNmNmMTdhMTFlNTlhZGE3YTk3YTU2N2FiOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HBJ9-aFiU52bKKCA0OD8olJO0j78EnCkkui8iN9RHGc)
> 
> p.s. 但我刚刚发现如果是用键盘移动光标的话这个 icon 不会变


确实，这个问题有点麻烦

**Comment by choyy** [comment]
> > 光标不在代码快内是没有内容的，光标在代码块内会返回该代码块的
> 
> 我这边尝试了如下操作： 光标在空代码块内部 光标在空块内部 光标在有内容的代码块内部 光标在空普通块内部 光标在有内容普通块内部 似乎都是一样的

不可能啊我都试过的，可惜现在手头没有电脑

**Comment by TCOTC** [comment]
@zxkmm 要不你看看打字机插件是怎么获取到当前焦点块的？

https://github.com/Zuoqiu-Yingyi/siyuan-plugin-typewriter

![image](https://github.com/user-attachments/assets/86434192-e3d7-4e42-8c6f-791d9275a5c2)

**Comment by zxkmm** [comment]
@choyy @TCOTC 感谢两位大佬，我再看看。因为这个粘贴事件是思源控制的，所以顺序可能有点难以处理（或者根本没法处理）我尽量看看

**Comment by choyy** [comment]
@zxkmm 
![图片](https://github.com/user-attachments/assets/fe7911cd-5a01-4864-baa7-a995a8f9f4a5)

**Comment by TCOTC** [comment]
我有个疑问啊，你的 .block-focus 是从哪来的？我这里最多也就是 .protyle-wysiwyg--select 和 .protyle-wysiwyg--hl

思源的代码里我也没找到 block-focus 。

https://github.com/user-attachments/assets/50191513-4a39-461a-8be1-680e0b8b7470

**Comment by choyy** [comment]
确实默认没有...才发现是主题自己加的，不过也发现选择光标所在的块也很简单，下面几行代码就能获得(block):

```js
    let block = window.getSelection()
        && window.getSelection().focusNode
        && window.getSelection().focusNode.parentElement; // 当前光标
    while (block != null && block.dataset.nodeId == null) block = block.parentElement;
```
